### ISSUE TITLE
Improve Hyades new contributor process

### ISSUE THREAD

**Issue by celskeggs** [sipb/homeworld#280]
We constructed a TODO list a couple of weeks back:

- [ ] Collect feedback from people who worked on Hyades but then stopped working on Hyades.
- [ ] Set up image-based deployment to make new members' testing jobs easier. (#86)
- [x] Set up easy local cluster launch
- [x] Set up ACI image branches (#281)
- [ ] Design a set of hands-on labs to explain certain elements of Hyades as a project and relevant elements of systems engineering (#282)
- [x] Finalize chroot system (#275)
- [ ] Consider designing Hyades posters
- [ ] Plug Hyades in course 6 classes
- [x] Revise April deadline

**Comment by celskeggs** [comment]
This is an outdated administrative tasklist. Closing.
