### ISSUE TITLE
Improve testing velocity

### ISSUE THREAD

**Issue by celskeggs** [sipb/homeworld#83]
The last cluster deploy for DC4 took a number of days over the course of most of a week to complete; although this was affected by the number of changes needed to make DC4 work in practice, we need to figure out better ways to rebuild the cluster to test changes.

This may be punted past DC5 if necessary.

Components of this:

- [x] #62 Streamline ISO generation process to not require rebuilding packages
- [x] #71 Create installable package for administrative tools
- [x] #85 Automate cluster bringup verification
- [ ] #122 Finish automating cluster bringup -> #172
- [x] #87 Convert cluster administration tools to a common system

**Comment by celskeggs** [comment]
Components of this:

- [ ] #62 Streamline ISO generation process to not require rebuilding packages
- [ ] #71 Create installable package for administrative tools
- [ ] #85 Automate cluster bringup verification
- ??

**Comment by celskeggs** [comment]
Punting to DC6; adding #122 as part of this.

**Comment by celskeggs** [comment]
Since this is entirely reducible to #172, which should be the last part of this issue at this point, I'm closing this.
